### ISSUE TITLE
Minitest support

### ISSUE THREAD

**Issue by markedmondson** [Casecommons/with_model#30]
There seem to be a couple of sticky points to full minitest support. Namely:

a) The Minitest `setup` block executes before with_model so the class is not accessible. In Minitest, this block is similar to `before(:all)` in RSpec so used widely in initializing the test scenario.
b) There's a hard-coded call to [before](https://github.com/Casecommons/with_model/blob/master/lib/with_model.rb#L18-L20) in the `with_model` block, which isn't supported by Minitest. It's possible to get around it with a `extend Minitest::Spec::DSL` but that seems a bit unfortunate.

Any directions on how best to resolve? I'm happy to submit a PR, just looking for guidance and perhaps willingness to persevere on a solution.

**Comment by amarshall** [comment]
Myself and nertzy are mostly RSpec users, so for Minitest issues, a full runnable example would be helpful (showing I suppose what you expect a test to look like and then why that doesn’t work). Unfortunately, the Minitest compatibility is not presently in the automated tests.

**Comment by jpgeek** [comment]
Hey there,

A super simple way is to just use the WithModel::Model::DSL API, and use block setup/ teardown for the 
Model rather than implicit/ automagic.  This requires no modification at all to WithModel, but might be nice to push the `define_model` and `within_model` into WithModel somewhere.

`class WithModelTest < ActiveSupport::TestCase

  extend WithModel

  self.use_transactional_tests = false
  require 'database_cleaner'
  DatabaseCleaner.strategy = :truncation

  def teardown
    DatabaseCleaner.clean 
  end

  def define_model(name, **options, &block)
    WithModel::Model.new(name, **options).tap do |model|
      dsl = WithModel::Model::DSL.new model
      dsl.instance_exec(&block) if block
    end
  end

  def within_model(model, &block)
    model.create
    yield
    model.destroy
  end
end
`

In your tests you can then do:

`require 'test_helper'
class DummyTest < WithModelTest 

  def with_model_dummy
    define_model :DummyClass do
      table do |t|
        t.string :title
        t.timestamps null: false
      end

      # The model block is the ActiveRecord model’s class body.
      model do
        include Foo
        # ...
      end
    end
  end

  def test_validates_stuff
    within_model(with_model_dummy) do
      instance = DummyClass.create
      assert instance.respond_to?(:foo_method)
    end
  end
end
`

Might want to change within_model to yield the class or otherwise make this more clever, but this is working for me now.

**Comment by miks** [comment]
@amarshall can we do a release? Maybe 2.2.0 as minitest is a new feature?

**Comment by jpgeek** [comment]
@amarshall,  release for 2.2.0 would be super duper nice.  The readme on the site now references a method (runner=) which does not exist in the released gem which is confusing.

**Comment by elsurudo** [comment]
Any ETA on a release?

**Comment by nertzy** [comment]
Released 2.1.6 with minitest support.
